In [3]:
import pandas as pd

In [7]:

data  = pd.read_csv('ElectricCarData_Clean.csv')

In [8]:
data.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997

In [10]:
data.value_counts()

Brand        Model                 AccelSec  TopSpeed_KmH  Range_Km  Efficiency_WhKm  FastCharge_KmH  RapidCharge  PowerTrain  PlugType    BodyStyle  Segment  Seats  PriceEuro
Aiways       U5                    9.0       150           335       188              350             Yes          FWD         Type 2 CCS  SUV        C        5      36057        1
Audi         Q4 Sportback e-tron   6.3       180           410       188              550             Yes          AWD         Type 2 CCS  SUV        D        5      57500        1
             Q4 e-tron             6.3       180           400       193              540             Yes          AWD         Type 2 CCS  SUV        D        5      55000        1
             e-tron 50 quattro     6.8       190           280       231              450             Yes          AWD         Type 2 CCS  SUV        E        5      67358        1
             e-tron 55 quattro     5.7       200           365       237              590             Yes          AWD         Type 2 CCS  SUV        E        5      79445        1
                                                                                                                                                                                  ..
Volkswagen   ID.3 Pure             10.0      160           270       167              250             Yes          RWD         Type 2 CCS  Hatchback  C        5      30000        1
             ID.4                  7.5       160           420       183              560             Yes          RWD         Type 2 CCS  SUV        C        5      45000        1
             e-Golf                9.6       150           190       168              220             Yes          FWD         Type 2 CCS  Hatchback  C        5      31900        1
             e-Up!                 11.9      130           195       166              170             Yes          FWD         Type 2 CCS  Hatchback  A        4      21421        1
Volvo        XC40 P8 AWD Recharge  4.9       180           375       200              470             Yes          AWD         Type 2 CCS  SUV        C        5      60437        1
Name: count, Length: 103, dtype: int64

In [11]:
data.tail(2)

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
101,Nissan,Ariya e-4ORCE 87kWh Performance,5.1,200,375,232,450,Yes,AWD,Type 2 CCS,Hatchback,C,5,65000
102,Byton,M-Byte 95 kWh 2WD,7.5,190,400,238,480,Yes,AWD,Type 2 CCS,SUV,E,5,62000

In [12]:
len(data.columns)

14

In [ ]:
data.shape

(103, 14)

In [19]:
data = data.rename(columns={'Brand':'Brands'})
data.head(2)

,Brands,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000

In [24]:
data.groupby('BodyStyle')['Brands'].count()

BodyStyle
Cabrio        3
Hatchback    32
Liftback      5
MPV           1
Pickup        3
SPV           3
SUV          45
Sedan        10
Station       1
Name: Brands, dtype: int64

In [26]:
data.groupby(['BodyStyle','Seats','RapidCharge'])['Brands'].count()

BodyStyle  Seats  RapidCharge
Cabrio     2      No              1
           4      Yes             2
Hatchback  2      No              1
           4      No              2
                  Yes            11
           5      Yes            18
Liftback   5      Yes             5
MPV        5      Yes             1
Pickup     6      Yes             3
SPV        5      No              1
           7      Yes             2
SUV        5      Yes            41
           7      Yes             4
Sedan      4      Yes             5
           5      Yes             5
Station    4      Yes             1
Name: Brands, dtype: int64